icon: settings
label: arnoson.kirby-forms.settings
sections:
  form_save: sections/form-save
  form_submit: sections/form-submit
  form_success: sections/form-success
  form_error: sections/form-error
  form_confirmation_email: sections/form-confirmation-email
  form_notification_email: sections/form-notification-email
  brevo: sections/form-brevo
